# Generated by Django 3.1 on 2020-08-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200814_1057'),
        ('catalog', '0003_auto_20200812_0523'),
    ]

    operations = [
    ]
